setupcheck:
    path: /api/setup-check
    controller: App\Controller\DefaultController::setupCheck

# Import currency routes
currency_routes:
    resource: 'routes/currency.yaml'

index:
    path: /{wildcard}
    defaults: {
        _controller: App\Controller\DefaultController::index
    }
    requirements:
        wildcard: .*
    # controller: App\Controller\DefaultController::index

